version: '3.7'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-cont
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: django-cont
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"
    links:
      - redis
  db:
    image: postgres:latest
    container_name: postgres-cont
  redis:
    image: redis:latest
    container_name: redis-cont
    ports:
     - '6379:6379'
